### ISSUE TITLE
[win64] Assertion failed - net.h:485

### ISSUE THREAD

**Issue by oti-dev** [zcoinofficial/zcoin#169] opened 2018-01-16 14:17 UTC
Hello,

I've come upon a disturbing issue. A node was running for a couple days in order to sync and 'acclimate', then this happened: 
![image](https://user-images.githubusercontent.com/33955426/34992988-388f296a-facf-11e7-8953-af959bd175ad.png)

It looks like a node connection was attempted to be closed twice. Is this issue known to you? Any idea what could've happened?

I must say I've made changes to zcoin code - the node was running on a build of this branch: https://github.com/oti-dev/zcoin/tree/utxo_doublespends_dirty
However I'm not aware of any of my modification having influence on CNode class and connection management.  I'd be thankful for any advices on working this out.

**Comment by schinzelh** [comment] 2018-01-23 10:50
The issue is known, same happens on Linux for me. There is a mutex lock missing to protect a variable - I'll submit a PR to fix it.

**Comment by azilber** [comment] 2018-02-03 04:25
Getting the same error.  Devs, please review PR.

**Comment by riordant** [comment] 2018-04-24 09:04
@azilber the fix was merged in the referenced issue.

**Closed by riordant** 2018-04-24 09:04 UTC
