### ISSUE TITLE
Fatal Error During Sigma Spend

### ISSUE THREAD

**Issue by catchingknives** [zcoinofficial/zcoin#688] opened 2019-09-17 10:37 UTC
## Actual behaviour
Popup `A fatal error occured. Zcoin can no longer continue safely and will quit` after spending

## Desired behaviour
Spend goes through without crash

## Steps to reproduce
Unknown. Log available [here](https://teamzcoin.slack.com/files/U96LX4C0H/FN8E254UR/debug.log)

**Comment by qashban4** [comment] 2019-10-11 05:28
@levonpetrosyan93  spent 3 days debugging but no result, could not find any reason.

**Comment by qashban4** [comment] 2019-10-11 06:24
@reubenyap  couldn't reproduce. We decide to close it and revisit if its reproduced again.

**Closed by qashban4** 2019-10-11 06:24 UTC
Labels: bug
