### ISSUE TITLE
compile completed, wallet updated, then I got CreateNewBlock: TestBlockValidity

### ISSUE THREAD

**Issue by splxsg** [zcoinofficial/zcoin#119] opened 2017-09-21 08:03 UTC
Hi guy

I just upgraded to the new wallet. everthing goes perfect. The wallet has synchronized on the mainnet. However, when I try to obtain a new block by using ./zcoin-cli getblocktemplate it comes the error following:

CreateNewBlock: TestBlockValidity failed: bad-cb-height, block height mismatch in coinbase (code 16)

Can anyone have any idea about this?

**Comment by reubenyap** [comment] 2017-09-21 09:58
Duplicate of https://github.com/zcoinofficial/zcoin/issues/120

Will consolidate there.

**Closed by reubenyap** 2017-09-21 09:58 UTC
